version: '3.5'

services:
  mongodb:
    image: mongo:latest
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sample
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongodb:27017 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - node-app
    depends_on:
      - mongodb
  
networks: 
  node-app:
    driver: bridge  

volumes:
  data: